# version: "3.9"

# services:
#   orchestrator:
#     build: ./services/orchestrator
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./services/orchestrator/uploads:/app/uploads

version: "3.9"

services:
  orchestrator:
    build: ./services/orchestrator
    ports:
      - "8000:8000"
    volumes:
      - ./services/orchestrator/uploads:/app/uploads

  efr_db:
    build: ./services/efr_db
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  form_filler:
    build: ./services/form_filler
    ports:
      - "8002:8002"
    volumes:
    - ./services/form_filler/forms:/app/forms

  status_tracker:
    build: ./services/status_tracker
    ports:
      - "8003:8003"


volumes:
  mongo_data:
