import { Language } from '@/types';

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
];

export const TRANSLATIONS = {
  en: {
    title: 'Sanchalak - Government Scheme Assistant',
    subtitle: 'Your digital guide to government schemes and benefits',
    welcomeMessage: 'Welcome! I\'m here to help you with government schemes and benefits. How can I assist you today?',
    placeholderText: 'Type your question about government schemes...',
    recordingText: 'Recording...',
    processingText: 'Processing...',
    sendButton: 'Send',
    recordButton: 'Record Voice',
    languageLabel: 'Language',
    errorTitle: 'Error',
    errorNetwork: 'Network error. Please check your connection.',
    errorRecording: 'Recording failed. Please try again.',
    errorPlayback: 'Audio playback failed.',
    noMicrophone: 'Microphone access denied. Please allow microphone permissions.',
    chatHistory: 'Chat History',
    clearChat: 'Clear Chat',
    speaking: 'Speaking...',
  },
  hi: {
    title: 'संचालक - सरकारी योजना सहायक',
    subtitle: 'सरकारी योजनाओं और लाभों के लिए आपका डिजिटल गाइड',
    welcomeMessage: 'स्वागत है! मैं सरकारी योजनाओं और लाभों में आपकी सहायता के लिए यहाँ हूँ। आज मैं आपकी कैसे सहायता कर सकता हूँ?',
    placeholderText: 'सरकारी योजनाओं के बारे में अपना प्रश्न लिखें...',
    recordingText: 'रिकॉर्डिंग...',
    processingText: 'प्रोसेसिंग...',
    sendButton: 'भेजें',
    recordButton: 'आवाज रिकॉर्ड करें',
    languageLabel: 'भाषा',
    errorTitle: 'त्रुटि',
    errorNetwork: 'नेटवर्क त्रुटि। कृपया अपना कनेक्शन जांचें।',
    errorRecording: 'रिकॉर्डिंग असफल। कृपया पुनः प्रयास करें।',
    errorPlayback: 'ऑडियो प्लेबैक असफल।',
    noMicrophone: 'माइक्रोफोन पहुंच अस्वीकृत। कृपया माइक्रोफोन अनुमतियां दें।',
    chatHistory: 'चैट इतिहास',
    clearChat: 'चैट साफ़ करें',
    speaking: 'बोल रहा है...',
  },
  gu: {
    title: 'સંચાલક - સરકારી યોજના સહાયક',
    subtitle: 'સરકારી યોજનાઓ અને લાભો માટે તમારો ડિજિટલ માર્ગદર્શક',
    welcomeMessage: 'સ્વાગત છે! હું સરકારી યોજનાઓ અને લાભોમાં તમારી સહાય માટે અહીં છું। આજે હું તમારી કેવી રીતે મદદ કરી શકું?',
    placeholderText: 'સરકારી યોજનાઓ વિશે તમારો પ્રશ્ન લખો...',
    recordingText: 'રેકોર્ડિંગ...',
    processingText: 'પ્રોસેસિંગ...',
    sendButton: 'મોકલો',
    recordButton: 'અવાજ રેકોર્ડ કરો',
    languageLabel: 'ભાષા',
    errorTitle: 'ભૂલ',
    errorNetwork: 'નેટવર્ક એરર. કૃપા કરીને તમારું કનેક્શન ચેક કરો.',
    errorRecording: 'રેકોર્ડિંગ નિષ્ફળ. કૃપા કરીને ફરીથી પ્રયાસ કરો.',
    errorPlayback: 'ઓડિયો પ્લેબેક નિષ્ફળ.',
    noMicrophone: 'માઇક્રોફોન એક્સેસ નકારવામાં આવ્યો. કૃપા કરીને માઇક્રોફોન પરમિશન આપો.',
    chatHistory: 'ચેટ ઇતિહાસ',
    clearChat: 'ચેટ સાફ કરો',
    speaking: 'બોલી રહ્યું છે...',
  },
  // Add more translations for other languages...
  pa: {
    title: 'ਸੰਚਾਲਕ - ਸਰਕਾਰੀ ਯੋਜਨਾ ਸਹਾਇਕ',
    subtitle: 'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਅਤੇ ਲਾਭਾਂ ਲਈ ਤੁਹਾਡਾ ਡਿਜੀਟਲ ਗਾਈਡ',
    welcomeMessage: 'ਸੁਆਗਤ ਹੈ! ਮੈਂ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਅਤੇ ਲਾਭਾਂ ਵਿੱਚ ਤੁਹਾਡੀ ਸਹਾਇਤਾ ਲਈ ਇੱਥੇ ਹਾਂ। ਅੱਜ ਮੈਂ ਤੁਹਾਡੀ ਕਿਵੇਂ ਸਹਾਇਤਾ ਕਰ ਸਕਦਾ ਹਾਂ?',
    placeholderText: 'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਬਾਰੇ ਆਪਣਾ ਸਵਾਲ ਲਿਖੋ...',
    recordingText: 'ਰਿਕਾਰਡਿੰਗ...',
    processingText: 'ਪ੍ਰੋਸੈਸਿੰਗ...',
    sendButton: 'ਭੇਜੋ',
    recordButton: 'ਆਵਾਜ਼ ਰਿਕਾਰਡ ਕਰੋ',
    languageLabel: 'ਭਾਸ਼ਾ',
    errorTitle: 'ਗਲਤੀ',
    errorNetwork: 'ਨੈੱਟਵਰਕ ਐਰਰ। ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਕਨੈਕਸ਼ਨ ਚੈਕ ਕਰੋ।',
    errorRecording: 'ਰਿਕਾਰਡਿੰਗ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    errorPlayback: 'ਆਡੀਓ ਪਲੇਬੈਕ ਅਸਫਲ।',
    noMicrophone: 'ਮਾਈਕ੍ਰੋਫੋਨ ਐਕਸੈਸ ਮਨ੍ਹਾ। ਕਿਰਪਾ ਕਰਕੇ ਮਾਈਕ੍ਰੋਫੋਨ ਇਜਾਜ਼ਤਾਂ ਦਿਓ।',
    chatHistory: 'ਚੈਟ ਇਤਿਹਾਸ',
    clearChat: 'ਚੈਟ ਸਾਫ਼ ਕਰੋ',
    speaking: 'ਬੋਲ ਰਿਹਾ ਹੈ...',
  },
  bn: {
    title: 'সঞ্চালক - সরকারি প্রকল্প সহায়ক',
    subtitle: 'সরকারি প্রকল্প এবং সুবিধার জন্য আপনার ডিজিটাল গাইড',
    welcomeMessage: 'স্বাগতম! আমি সরকারি প্রকল্প এবং সুবিধায় আপনাকে সাহায্য করার জন্য এখানে আছি। আজ আমি আপনাকে কীভাবে সাহায্য করতে পারি?',
    placeholderText: 'সরকারি প্রকল্প সম্পর্কে আপনার প্রশ্ন লিখুন...',
    recordingText: 'রেকর্ডিং...',
    processingText: 'প্রক্রিয়াকরণ...',
    sendButton: 'পাঠান',
    recordButton: 'কণ্ঠস্বর রেকর্ড করুন',
    languageLabel: 'ভাষা',
    errorTitle: 'ত্রুটি',
    errorNetwork: 'নেটওয়ার্ক ত্রুটি। অনুগ্রহ করে আপনার সংযোগ পরীক্ষা করুন।',
    errorRecording: 'রেকর্ডিং ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।',
    errorPlayback: 'অডিও প্লেব্যাক ব্যর্থ।',
    noMicrophone: 'মাইক্রোফোন অ্যাক্সেস অস্বীকৃত। অনুগ্রহ করে মাইক্রোফোন অনুমতি দিন।',
    chatHistory: 'চ্যাট ইতিহাস',
    clearChat: 'চ্যাট পরিষ্কার করুন',
    speaking: 'কথা বলছে...',
  },
};

export const getTranslation = (language: string, key: string): string => {
  const translations = TRANSLATIONS[language as keyof typeof TRANSLATIONS] || TRANSLATIONS.en;
  return translations[key as keyof typeof translations] || TRANSLATIONS.en[key as keyof typeof TRANSLATIONS.en] || key;
};
