FROM swipl:latest

RUN apt-get update && apt-get install -y python3 python3-pip

WORKDIR /app
COPY src/scheme_server /app
COPY src/pipeline /app/pipeline
COPY src/scheme_server/outputs/pm-kisan/REFERENCE_prolog_system.pl /app/outputs/pm-kisan/REFERENCE_prolog_system.pl
COPY src/efr_server/requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 8002
CMD ["python3", "scheme_backend.py"] 