FROM python:3.10-slim

WORKDIR /app
COPY src/schemabot /app
COPY src/pipeline /app/pipeline
COPY src/schemabot/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8003
CMD ["python", "api/graphql_server.py"] 